version: '3.8'

services:
  eureka-server:
    container_name: eureka-server-container
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - projet-poly_microservices-network
    environment:
      - spring.application.name=EUREKA-SERVER
      - server.port=8761

  api-gateway:
    container_name: api-gateway-container
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    networks:
      - projet-poly_microservices-network
    environment:
      - spring.application.name=APIGATEWAY
      - server.port=8080
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  bairstowresolution:
    container_name: bairstowresolution-container
    build:
      context: ./BairstowResolution
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
    networks:
      - projet-poly_microservices-network
    environment:
      - SPRING_APPLICATION_NAME=BAIRSTOWRESOLUTION
      - SERVER_PORT=8086
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_INSTANCE_ID=BAIRSTOWRESOLUTION:8086
      - EUREKA_CLIENT_INITIAL_INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS=5
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=5
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always

  cardanosresolution:
    container_name: cardanosresolution-container
    build:
      context: ./CardanosResolution
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - projet-poly_microservices-network
    environment:
      - SPRING_APPLICATION_NAME=CARDANOSRESOLUTION
      - SERVER_PORT=8083
      - SERVER_SERVLET_CONTEXT_PATH=/
      - SERVER_TOMCAT_RELAXED_QUERY_CHARS=^,`,[,],{
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_INSTANCE_ID=CARDANOSRESOLUTION:8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true

networks:
  projet-poly_microservices-network:
    external: true
